version: "3"
services:
  frontend:
    image: docker-front
    deploy:
      replicas: 1
    ports:
      - "3000:80"

  main-service:
    image: docker-main-service
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    links:
      - logstash
    
  eureka-server:
    image: docker-eureka-server
    deploy:
      replicas: 1
    ports:
      - "8761:8761"
      
  user-service:
    image: docker-user-service
    deploy:
      replicas: 1
    ports:
      - "8081:8081"
      
  history-service:
    image: docker-history-service
    deploy:
      replicas: 1
    ports:
      - "8082:8082"

  elasticsearch:
    build: elk/elasticsearch/
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      
  logstash:
    build: elk/logstash/
    container_name: logstash
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./elk/logstash/config:/etc/logstash/conf.d
    ports:
      - "9999:9999"
    links:
      - elasticsearch

  kibana:
    build: elk/kibana/
    container_name: kibana
    volumes:
      - ./elk/kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    links:
      - elasticsearch


